dist: xenial
language: python
cache: false
env:
  global:
    - PYTEST_ADDOPTS=--cov-report=xml
jobs:
  include:
    - env: TOXENV=py36-coverage
      python: "3.6"
    - env: TOXENV=py37-coverage
      python: "3.7"
    - env: TOXENV=py38-coverage
      python: "3.8"
    - env: TOXENV=checkqa
      python: "3.7"
install: pip install tox
script: tox
after_script:
  - |
    # Upload coverage.
    if [[ -f coverage.xml ]]; then
      pip install codecov
      codecov -f coverage.xml
    fi
branches:
  only:
    - master
    - next
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
